version: "3.3"
services:
  rpc_bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$RPC_PORT:8080"
    volumes:
      - "$JWT_PUBLIC_KEY_FILE:/jwt.key.pub"
    env_file:
      - .env
