// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: proto/foxbot_gateway.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PersistRoleData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId     string               `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UserId     string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GuildId    string               `protobuf:"bytes,3,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Expiration *timestamp.Timestamp `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
}

func (x *PersistRoleData) Reset() {
	*x = PersistRoleData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_foxbot_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersistRoleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistRoleData) ProtoMessage() {}

func (x *PersistRoleData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_foxbot_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistRoleData.ProtoReflect.Descriptor instead.
func (*PersistRoleData) Descriptor() ([]byte, []int) {
	return file_proto_foxbot_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *PersistRoleData) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *PersistRoleData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PersistRoleData) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *PersistRoleData) GetExpiration() *timestamp.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type UnpersistRoleData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId     string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GuildId    string `protobuf:"bytes,3,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	RemoveRole bool   `protobuf:"varint,4,opt,name=remove_role,json=removeRole,proto3" json:"remove_role,omitempty"`
}

func (x *UnpersistRoleData) Reset() {
	*x = UnpersistRoleData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_foxbot_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnpersistRoleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpersistRoleData) ProtoMessage() {}

func (x *UnpersistRoleData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_foxbot_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpersistRoleData.ProtoReflect.Descriptor instead.
func (*UnpersistRoleData) Descriptor() ([]byte, []int) {
	return file_proto_foxbot_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *UnpersistRoleData) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UnpersistRoleData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnpersistRoleData) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *UnpersistRoleData) GetRemoveRole() bool {
	if x != nil {
		return x.RemoveRole
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_foxbot_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_foxbot_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_foxbot_gateway_proto_rawDescGZIP(), []int{2}
}

var File_proto_foxbot_gateway_proto protoreflect.FileDescriptor

var file_proto_foxbot_gateway_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6f, 0x78, 0x62, 0x6f, 0x74, 0x5f, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a, 0x01,
	0x0a, 0x0f, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x3a,
	0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x81, 0x01, 0x0a, 0x11, 0x55,
	0x6e, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x07,
	0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x65, 0x0a, 0x0d, 0x46, 0x6f, 0x78, 0x62, 0x6f,
	0x74, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x27, 0x0a, 0x0b, 0x50, 0x65, 0x72, 0x73,
	0x69, 0x73, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73,
	0x74, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x06, 0x2e, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x2b, 0x0a, 0x0d, 0x55, 0x6e, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x52, 0x6f,
	0x6c, 0x65, 0x12, 0x12, 0x2e, 0x55, 0x6e, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x52, 0x6f,
	0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x06, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x28,
	0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x61,
	0x6c, 0x6c, 0x79, 0x2f, 0x66, 0x6f, 0x78, 0x62, 0x6f, 0x74, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_foxbot_gateway_proto_rawDescOnce sync.Once
	file_proto_foxbot_gateway_proto_rawDescData = file_proto_foxbot_gateway_proto_rawDesc
)

func file_proto_foxbot_gateway_proto_rawDescGZIP() []byte {
	file_proto_foxbot_gateway_proto_rawDescOnce.Do(func() {
		file_proto_foxbot_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_foxbot_gateway_proto_rawDescData)
	})
	return file_proto_foxbot_gateway_proto_rawDescData
}

var file_proto_foxbot_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_foxbot_gateway_proto_goTypes = []interface{}{
	(*PersistRoleData)(nil),     // 0: PersistRoleData
	(*UnpersistRoleData)(nil),   // 1: UnpersistRoleData
	(*Empty)(nil),               // 2: empty
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_foxbot_gateway_proto_depIdxs = []int32{
	3, // 0: PersistRoleData.expiration:type_name -> google.protobuf.Timestamp
	0, // 1: FoxbotGateway.PersistRole:input_type -> PersistRoleData
	1, // 2: FoxbotGateway.UnpersistRole:input_type -> UnpersistRoleData
	2, // 3: FoxbotGateway.PersistRole:output_type -> empty
	2, // 4: FoxbotGateway.UnpersistRole:output_type -> empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_foxbot_gateway_proto_init() }
func file_proto_foxbot_gateway_proto_init() {
	if File_proto_foxbot_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_foxbot_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersistRoleData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_foxbot_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnpersistRoleData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_foxbot_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_foxbot_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_foxbot_gateway_proto_goTypes,
		DependencyIndexes: file_proto_foxbot_gateway_proto_depIdxs,
		MessageInfos:      file_proto_foxbot_gateway_proto_msgTypes,
	}.Build()
	File_proto_foxbot_gateway_proto = out.File
	file_proto_foxbot_gateway_proto_rawDesc = nil
	file_proto_foxbot_gateway_proto_goTypes = nil
	file_proto_foxbot_gateway_proto_depIdxs = nil
}
